import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "@/app/session-provider-wrapper";
import { LoadingProvider } from "../context/loading";
import { ThemeProvider } from "@/context/theme";
// import { Toaster } from "sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "dash",
  description: "Generated by create dash anality",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <SessionProviderWrapper>
          <LoadingProvider>
            <ThemeProvider>
              {/* <Toaster /> */}
              {children}
            </ThemeProvider>
          </LoadingProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
